import "./index.css"
import "primereact/resources/themes/saga-blue/theme.css"
import "primereact/resources/primereact.min.css"

import Footer from "./Components/Footer/Footer"
import Navbar from "./Components/Navbar/Navbar"
// import 'primeicons/primeicons.css';
// import 'primeflex/primeflex.css';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
